#!/usr/bin/env bash
#Transferring a file from client to a server

if(($# == 4)); then
       scp -i -o StrictHostKeyChecking=no "$1" "$4" "$3"@"$2":~
else
	echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
fi
