#!/usr/bin/env bash
#Permanently redirecting

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i '26i\      rewrite ^\/redirect_me\/ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
