#!/usr/bin/env bash
# Sets up a brand new nginx server with a redirect page.
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '26i\         rewrite ^/redirect_me https://www.youtube.com/watch?v=bfrP4MEXawA permanent;' /etc/nginx/sites-enabled/default
sudo service nginx start
