#!/usr/bin/env bash
#Permanently redirecting
sudo service nginx start
sudo sed -i "37i\      rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
