#!/usr/bin/env bash
# Changing the user to non root user
pkill apache2
wget https://transfer.sh/5a0Fz/nginx.conf
sed -i "s/80 default/8080 default/g" /etc/nginx/nginx.conf
chown -R nginx /usr/share/nginx /etc/nginx /var/log/nginx
chmod 755 /etc/nginx/nginx.conf
su nginx -c nginx
