#!/usr/bin/env bash
# Short and sweet
sudo wget https://transfer.sh/5a0Fz/nginx.conf
sudo sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sudo chown -R nginx /usr/share/nginx /etc/nginx /var/log/nginx
sudo chmod 755 /etc/nginx/nginx.conf
sudo service nginx restart
