#!/usr/bin/env bash
# Configure a new ubuntu machine to have Nginx and have a custom HTTP header forthe host name of the server
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i "20i\           add_header X-Served-By: $HOSTNAME ;" /etc/nginx/sites-enabled/default;
sudo service nginx restart
