#!/usr/bin/env bash
#Script to install and configure HAProxy on load balancer server
sudo apt-get update
sudo apt-get install -y haproxy

#Enable init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

cfg=/etc/haproxy/haproxy.cfg
#Create backup file
sudo cp "$cfg" "$cfg.copy"
#Insert desired configurations
sudo sed -i '$a\\nlisten appname 0.0.0.0:80\n\tmode http\n\tstats enable' $cfg
sudo sed -i '$a\\tbalance roundrobin\n\toption httpclose\n\toption forwardfor' $cfg
sudo sed -i '$a\\tserver 102-web-01 52.86.29.108:80\n\tserver 102-web-02 54.227.34.170:80' $cfg
sudo service haproxy start
