#!/usr/bin/env bash
# Printing "I am invincible!!!" everytime a SIGTERM signal is received.
trap "echo I am invincible!!!" SIGTERM
while (true); do
      echo "To infinity and beyond"
      sleep 2
done
