#!/usr/bin/env bash
#Deleting the file in a directory when receiving a SIGQUIT or SIGTERM signal
trap "echo Y U no love me?!;" SIGINT
trap "sudo rm /var/run/holbertonscript.pid;
echo I hate the kill command; exit" SIGQUIT SIGTERM
while (true); do
      echo "To infinity and beyond"
      sleep 2
done
