#!/usr/bin/env bash
#Prints "Hi" on the 9th iteration and "Holberton School" on all other iterations

i=0
while ((i < 10))
      do
      echo "Holberton School";
      if ((i == 8));
      then
	  echo "Hi";
      fi
      ((i++))
done
