#!/usr/bin/env bash
#Displays time for 12 hours and 59 minutes.


i=0
while ((i < 13)); do
      echo "Hour: $i"

      j=0
      while ((j <= 59)); do
	  echo "$j"
          ((j++))
      done
((i++))
done
