#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements
cp /etc/hosts /etc/hosts.backup
sed -i 's/127.0.0.1 localhost/127.0.0.2' /etc/hosts
sed -i '$ a8.8.8.8 facebook.com' /etc/hosts
