#!/bin/bash
#Prints "Hi" on the 9th iteration and "Holberton School" on all other iterations

i=0
while ((i < 10))
      do
      if ((i == 8));
      then
	  echo "hi";
      else
	 echo "Holberton School";
      fi
      ((i++))
done
